#\!/bin/bash
echo "=================================="
echo "Quick Database Setup"
echo "=================================="
echo ""
echo "Step 1: Create .env file"
echo "  cp .env.template .env"
echo ""
echo "Step 2: Edit .env and fill in:"
echo "  - DATABASE_URL (get from Neon.tech or use local PostgreSQL)"
echo "  - ADMIN_PASSWORD (choose a secure password)"
echo "  - SESSION_SECRET (run: openssl rand -base64 32)"
echo ""
echo "Step 3: Apply migrations"
echo "  bash setup-db.sh"
echo ""
echo "See SETUP_INSTRUCTIONS.md for detailed guidance"
echo ""
